site_name: manual_user_new

nav:
  - index.md
  - Basic concepts:
    - basic_concepts/index.md
    - Requirements: "basic_concepts/Requirements_OpenOlat.md"
    - Roles and Rights:
      - Overview: "basic_concepts/Roles_Rights.md"
      - Authorisation concept: "basic_concepts/Authorisation_Concept.md"
      - Coach: "basic_concepts/coach.md"
      - Guest access: "basic_concepts/guest_access.md"
    - Account:
      - Session Timeout and Logout: "basic_concepts/Session_Timeout_and_Logout.md"  
    - Framework:
      - Navigation: "basic_concepts/Navigation.md"
      - Full-Text Search: "basic_concepts/Full_Text_Search.md"
      - Portal configuration: "basic_concepts/Portal_configuration.md"
      - Chat: "basic_concepts/Chat.md"
      - Table concept: "basic_concepts/Table_Concept.md"
      - Math formula: "basic_concepts/Math_formula.md"
    - Technology:
      - Overview: basic_concepts/Technology.md 
      - Using WebDAV: "basic_concepts/Using_WebDAV.md" 
      - Technology and Navigation: "basic_concepts/Technology_and_Navigation.md"
    
 
  - Login and registration:
    - login_registration/index.md
    - Login Page: "login_registration/Login_Page.md"

  - Personal menu:
    - personal_menu/index.md
    - Personal tools:
      - Calendar: "personal_menu/Calendar.md"
      - Personal folders: "personal_menu/Personal_folders.md"
      - E-Mail: "personal_menu/E-Mail.md"
    - Configuration:
      - Overview: "personal_menu/Configuration.md"
      - COVID certificate: "personal_menu/COVID_certificate.md"
 
  - Area and modules:
    - area_modules/index.md
    - Courses:
      - Overview: "area_modules/Courses.md"
      - Catalog 1.0: "area_modules/catalog1.0.md"
    - Catalog:
      - Catalog 2.0: "area_modules/catalog2.0.md"
    - Groups:
       - Group Management: "area_modules/Group_Management.md"
    - Coaching:
      - Overview: "area_modules/Coaching.md" 
    - Authoring:
       - Overview: "area_modules/Authoring.md"
       - Actions in the Authoring section: "area_modules/Authoring_BulkActions.md"
    - Question Bank:
      - Overview: "area_modules/Question_Bank.md"
      - Data Management: "area_modules/Data_Management.md"
      - Item Detailed View: "area_modules/Item_Detailed_View.md"
      - Question bank possible operations: "area_modules/Question_bank_possible_operations.md"
      - Search: "area_modules/Search.md"
      - Question Pool Sharing Options: "area_modules/Question_Pool_Sharing_Options.md"
      - Question Bank Review Process: "area_modules/Question_Bank_Review_Process.md"
      - Question Bank Administration: "area_modules/Question_Bank_Administration.md"
    - Curriculum Management: "area_modules/Curriculum_Management.md"

  - Learning resources:
    - learningresources/index.md
    - General functions:
      - Detailed View of Learning Resources: "learningresources/Detailed_View_of_Learning_Resources.md"
      - Set up info page: "learningresources/Set_up_info_page.md"
      - Technical Information on Resources and Usage: "learningresources Technical_Information_on_Resources_and_Usage.md"
      - Access configuration: "learningresources/Access_configuration.md"
    - Course:
      - Overview: "learningresources/General_Information.md"
      - Create course: "learningresources/Creating_Course.md"
      - Course design:
        - Overview: "learningresources/Learning_path_course.md"
        - Creating learning path courses: "learningresources/Creating_learning_path_courses.md"
        - Lernpfad Kurs: "learningresources/Learning_path_course_Course_editor.md"
        - Lernpfad Kurse: "learningresources/Learning_path_course_Participant_view.md"
      - Course editor:
        - Overview: "learningresources/General_Configuration_of_Course_Elements.md"
        - Deleting, Moving and Copying Course Elements: "learningresources/Deleting_Moving_and_Copying_Course_Elements.md"
        - Access Restrictions in the Expert Mode: "learningresources/Access_Restrictions_in_the_Expert_Mode.md"
        - Using additional Course Editor Tools: "learningresources/Using_additional_Course_Editor_Tools.md"
      - Toolbar:
        - Info page: "learningresources/Info_page.md"
        - Additional Course Features: "learningresources/Additional_Course_Features.md"
        - Using Additional Course Features: "learningresources/Using_Additional_Course_Features.md"
      - Administration:
        - Overview: "learningresources/Administration.md"
        - Overview: "learningresources/Using_Course_Tools.md"
        - Members management: "learningresources/Members_management.md"
        - Storage folder: "learningresources/Storage_folder.md"
        - Assessment tool :
          - Overview : "learningresources/Assessment_tool_overview.md"
          - Tab users: "learningresources/Assessment_tool_tab_Users.md"
          - Assessment of learners: "learningresources/Assessment_of_learners.md"
          - Assessment of course modules: "learningresources/Assessment_of_course_modules.md"
          - Assessing tasks and group tasks: "learningresources/Assessing_tasks_and_group_tasks.md"
          - Assessing tests: "learningresources/Assessing_tests.md"
          - The assessment form: "learningresources/The_assessment_form.md"
          - Grading / Evaluation Scale: "learningresources/Assessment_translate_points_in_grades.md"
          - Assess tasks: "learningresources/Assess_tasks.md"
          - Portfolio assignment Grading: "learningresources/Portfolio_assignment_Grading.md"
          - Forms in Rubric Scoring: "learningresources/Forms_in_Rubric_Scoring.md"
        - Lectures and absences:
          - Overview: "learningresources/Lectures_and_absences.md"
          - Lektionen : "learningresources/Lectures_User_view.md"
          - Lektionen : "learningresources/Lectures_Teacher_view.md"
        - Course Reminders: "learningresources/Course_Reminders.md"
        - Data archiving: "learningresources/Data_archiving.md"
        - Record of Course Activities: "learningresources/Record_of_Course_Activities.md"
        - Exams: "learningresources/Exams.md"
        - Assessment mode: "learningresources/Assessment_mode.md"
      - Settings:
        - Overview: "learningresources/Course_Settings.md"
        - LTI access: "learningresources/LTI_Share_courses.md"
        - Design possibilities of courses and course elements: "learningresources/Design_possibilities_of_courses_and_course_elements.md"
    - Course elements: 
      - Overview: "learningresources/Course_Elements.md"
      - Overview: "learningresources/Course_Elements_2.md"
      - Knowledge Transfer:
        - Overview: "learningresources/Knowledge_Transfer.md"
        - Course Element Structure: "learningresources/Course_Element_Structure.md"
        - Course Element Folder: "learningresources/Course_Element_Folder.md"
        - Course Element Single Page: "learningresources/Course_Element_Single_Page.md"
        - Single Page_Add_edit video: "learningresources/Single_Page_Add_edit_video.md"
        - Course Element SCORM Learning Content: "learningresources/Course_Element_SCORM_Learning_Content.md"
        - Course Element card2brain Flashcards: "learningresources/Course_Element_card2brain_Flashcards.md"
        - Course Element Mediasite: "learningresources/Course_Element_Mediasite.md"
        - Course Element_Video: "learningresources/Course_Element_Video.md"
      - Assessment: 
        - Overview: "learningresources/Assessment.md"
        - Performance assessment: "learningresources/Performance_assessment.md"
        - Course Element Assessment: "learningresources/Course_Element_Assessment.md"
        - Course Element Checklist: "learningresources/Course_Element_Checklist.md"
        - Working with Tasks and Group Tasks: "learningresources/Working_with_Tasks_and_Group_Tasks.md"
        - Course Element Task: "learningresources/Task.md"
        - Task - Further Configurations: "learningresources/Task_Further_Configurations.md"
        - Working with Tests: "learningresources/Working_with_Tests.md"
        - Tests at course level: "learningresources/Tests_at_course_level.md"
        - Creating Portfolio Tasks: "learningresources/Creating_Portfolio_Tasks.md"
        - Portfolio task and assignment Collecting and editing: "learningresources/Portfolio_task_and_assignment_Collecting_and_editing.md"
        - Forms in Forms Element: "learningresources/Forms_in_Forms_Element.md"
        - Forms in Questionnaires: "learningresources/Forms_in_Questionnaires.md"  
      - Communication and Collaboration:
        - Overview: "learningresources/Communication_and_Collaboration.md"
        - Course element Adobe Connect: "learningresources/Course_element_Adobe_Connect.md"
        - Course element BigBlueButton: "learningresources/Course_element_BigBlueButton.md"
        - BBB - Frequently asked questions : "learningresources/Frequentyl_asked_questions_-_BigBlueButton.md"
        - Course element GoToMeeting: "learningresources/Course_element_GoToMeeting.md"
        - Course element OpenMeetings: "learningresources/Course_element_OpenMeetings.md"
        - Course element vitero: "learningresources/Course_element_vitero.md"
        - Course element Microsoft Teams: "learningresources/Course_element_Microsoft_Teams.md"
        - Course element Zoom: "learningresources/Course_element_Zoom.md"
        - Zoom - Frequently asked questions : "learningresources/Frequentyl_asked_questions_Zoom.md"
        - Working with Forums: "learningresources/Working_with_Forums.md"
        - Working with Wiki: "learningresources/Working_with_Wiki.md"
      - Other:
         - Overview: "learningresources/Other.md"
         - Working with Topic Assignment: "learningresources/Working_with_Topic_Assignment.md"
         - Topic assigment: "learningresources/Topic_Assignment.md"
      - Administration and Organisation: "learningresources/Administration_and_Organisation.md"
    - Test:
      - Overview: "learningresources/Test.md"
      - General Information on Tests: "learningresources/General_Information_on_Tests.md"
      - Test editor QTI 2.1: 
        - Overview: "learningresources/Test_editor_QTI_2.1.md"
        - Test question types: "learningresources/Test_question_types.md"
        - Configure test questions: "learningresources/Configure_test_questions.md"
        - Configure tests: "learningresources/Configure_tests.md"
        - Test settings: "learningresources/Test_settings.md"
    - CP learning content:
       - CP Editor: "learningresources/CP_Editor.md"
    - Wiki:
      - Overview: "learningresources/Wiki.md"
    - Podcast:
      - Overview: "learningresources/Podcast.md"
      - Podcast: "learningresources/Podcast_Further_Configurations.md"
    - Blog:
       - Overview: "learningresources/Blog.md"
       - Blog: "learningresources/Blog_Further_Configurations.md"
    - Video:
      - Overview: "learningresources/Video.md"
      - Learning resource Video: "learningresources/Learning_resource_Video.md"
      - Video Upload: "learningresources/Video_Upload.md"
    - Resource folder:
      - Overview: "learningresources/Resource_Folder.md"
    - Form:
      - Overview: "learningresources/Form.md"
      - Forms in Courses: "learningresources/Forms_in_Courses.md"
      - General information on Forms: "learningresources/General_information_on_Forms.md"
      - Form editor (Questionnaire editor): 
        - Overview: "learningresources/Form_editor_Questionnaire_editor.md"
        - Form Editor 17.1: "learningresources/Form_editor_17_1.md"
        - Rubric: "learningresources/Rubric.md"
        - Question rules: "learningresources/Question_rules.md"
    - Portfolio 2.0 Template:
      - Portfolio template Creation: "learningresources/Portfolio_template_Creation.md"
      - Portfolio template Administration and editing: "learningresources/Portfolio_template_Administration_and_editing.md"
      - Forms in the ePortfolio template: "learningresources/Forms_in_the_ePortfolio_template.md"
    - Glossary:
      - Overview: "learningresources/Glossary.md"
   
  - Groups:
    - groups/index.md
    - Create Groups: "groups/Create_Groups.md"
    - Using Group Tools: "groups/Using_Group_Tools.md"
    - Administration: 
      - Group Administration: "groups/Group_Administration.md"
      - LTI access: "groups/LTI_Share_groups.md"

  - Portfolio:
    - portfolio/index.md
    - Portfolio - General Information: "portfolio/Portfolio_General_Information.md"
    - Components of the portfolio:
      - Overview: "portfolio/Components_of_the_portfolio.md"
      - My portfolio binders: "portfolio/My_portfolio_binders.md"
      - My entries: "portfolio/My_entries.md"
      - Media center: "portfolio/Media_center.md"
      - Shared by me: "portfolio/Shared_by_me.md"
      - Shared with me: "portfolio/Shared_with_me.md"
    - Multiple use of entries: "portfolio/Multiple_use_of_entries.md"
    - Competences tags: "portfolio/Competences_tags.md"
    - The portfolio editor: "portfolio/The_portfolio_editor.md"
    - The portfolio editor for 17.1: "portfolio/The_portfolio_editor_17_1.md"

  - Help:
    - help/index.md
    - Course Problems and Error Messages: "learningresources/Course_Problems_and_Error_Messages.md"

  - About us:
    - about/index.md
    - Information on OpenOlat: "about/Information_on_OpenOlat.md"
    - The Idea of Open-Source Software: "about/OpenSource_Software.md"