site_name: OpenOlat Documentation
site_url: https://docs.openolat.org

theme:
  name: material
  palette:
    - scheme: default
      primary: cyan
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: cyan
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: assets/favicon64.png
  logo: assets/OpenOlat_Button_Quadrat_RGB.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.sections
    
markdown_extensions:
  - meta
  - attr_list

#include_homepage_in_sidebar: false
#prev_next_buttons_location: none
#navigation_depth: 10
#collapse_navigation: true
#titles_only: false
#sticky_navigation: false

plugins:
  - monorepo
  - search
  - i18n:
      default_language: en
      languages:
        de: Deutsch
        en: English
      nav_translations:
        de:
          Start: Start
          Overview: Übersicht
          Imprint: Impressum
          License: Lizenz
          Release notes: Release Notes
          User manual: Benutzerhandbuch
          Admin manual: Administrationshandbuch
          Developer cookbook: Developer Cookbook
          
nav:
  - Start: 
    - Overview: index.md
    - Imprint: imprint.md
    - License: license.md
  - Release notes: '!include ./sites/release_notes/mkdocs.yml'
  - User manual: '!include ./sites/manual_user/mkdocs.yml' 
  - Admin manual: '!include ./sites/manual_admin/mkdocs.yml' 
  - Developer cookbook: '!include ./sites/manual_dev/mkdocs.yml' 

