site_name: OpenOlat Documentation
site_url: https://docs.openolat.org

theme:
  name: material
  palette:
    - scheme: default
      primary: cyan
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: cyan
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: assets/favicon64.png
  logo: assets/OpenOlat_Button_Quadrat_RGB.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
#    - navigation.sections
    
markdown_extensions:
  - meta
  - attr_list

#include_homepage_in_sidebar: false
#prev_next_buttons_location: none
#navigation_depth: 10
#collapse_navigation: true
#titles_only: false
#sticky_navigation: false

plugins:
  - monorepo
  - search
  - i18n:
      default_language: en
      languages:
        de: Deutsch
        en: English
      nav_translations:
        de:
          About this manual: Über dieses Handbuch
          Access configuration : Zugangskonfiguration
          Access Restrictions in the Expert Mode : Zugriffsbeschränkungen im Expertenmodus
          Actions in the Authoring section : Aktionen im Autorenbereich
          Additional Course Features : Zusätzliche Kursfunktionen
          Admin manual: Administrationshandbuch
          Administration : Administration
          Administration and Organisation : Verwaltung und Organisation
          Analytics module : Analytics Modul
          Assess tasks : Aufgaben bewerten
          Assessing tasks and group tasks : Aufgaben und Gruppenaufgaben bewerten
          Assessing tests : Tests bewerten
          Assessment : Wissensüberprüfung
          Assessment mode : Prüfungsmodus
          Assessment of course modules : Bewertung von Kursbausteinen
          Assessment of learners : Lernende bewerten
          Assessment tool : Bewertungswerkzeug
          Assign roles : Rollen zuweisen
          Aufgabe  : Aufgabe
          Authoring : Autorenbereich
          Automatic Group Lifecycle : Automatischer Gruppenlebenszyklus
          BBB - Frequentyl asked questions: BBB - Häuffig gestellte Fragen
          Bewertungswerkzeug  : Bewertungswerkzeug
          Bewertungswerkzeug  : Bewertungswerkzeug
          BigBlueButton module : Modul BigBlueButton
          Blog  : Blog
          Calendar : Kalender
          Chat : Chat
          Coach : Betreuer
          Coaching : Coaching
          Communication and Collaboration : Kommunikation und Kollaboration
          Competences tags : Kompetenzen verschlagworten
          Components of the portfolio : Bestandteile des Portfolios
          Configuration : Konfiguration
          Configure test questions : Test Fragen konfigurieren
          Configure tests : Test konfigurieren
          Configure User : Benutzer konfigurieren
          Core functions : Core Konfiguration
          Course Element Assessment : Kursbaustein Bewertung
          Course element BigBlueButton : Kursbaustein BigBlueButton
          Course Element card2brain Flashcards : Kursbaustein card2brain Lernkarten
          Course Element Checklist : Kursbaustein Checkliste
          Course Element Folder : Kursbaustein Ordner
          Course element GoToMeeting : Kursbaustein GoToMeeting
          Course element Microsoft Teams : Kursbaustein Microsoft Teams
          Course element OpenMeetings : Kursbaustein OpenMeetings
          Course Element SCORM Learning Content : Kursbaustein SCORM-Lerninhalt
          Course Element Single Page : Kursbaustein Einzelne Seite
          Course element vitero : Kursbaustein vitero
          Course Element_Video : Kursbaustein Video einrichten
          Course Operation : Kursbetrieb
          Course Problems and Error Messages : Probleme und Fehlermeldungen im Kurs
          Course Reminders : Erinnerung
          Course Settings : Kurseinstellungen
          Courses and Catalog : Kurse und Katalog
          COVID certificate : COVID Zertifikat
          CP Editor : CP Editor
          Create Groups : Gruppen erstellen
          Create User : Benutzer erstellen
          Creating Blogs : Blog erstellen
          Creating Courses : Kurs erstellen
          Creating CP Learning Content : CP-Lerninhalt erstellen
          Creating Forms : Formulare erstellen
          Creating learning path courses : Lernpfad Kurse erstellen
          Creating Podcasts : Podcast erstellen
          Creating Portfolio Tasks : Portfolioaufgabe erstellen
          Creating Portfolios : Portfolio erstellen
          Creating Tasks : Aufgabe erstellen
          Creating Tests : Tests erstellen
          Creating Videos : Video erstellen
          Creating Wikis : Wiki erstellen
          Curriculum Management : Curriculumverwaltung
          Customizing : Customizing
          Data archiving : Datenarchivierung
          Data Management : Handhabung der Daten
          Data protection : Datenschutz
          Deleting, Moving and Copying Course Elements : Löschen, Verschieben und Kopieren von Kursbausteinen
          Design possibilities of courses and course elements : Gestalterische Möglichkeiten von Kursen und Kursbausteinen
          Detailed View of Learning Resources : Detailansicht einer Lernressource
          Developer cookbook: Developer Cookbook
          e-Assessment Administration : e-Assessment Administration
          E-Mail : E-Mail
          E-Mail Settings : E-Mail Einstellungen
          eAssessment : Online Prüfungen
          eAssessment ePortfolio : e-Assessment ePortfolio
          eAssessment Question bank : e-Assessment Fragenpool
          Exams : Prüfungen
          Externe Werkzeuge  : Externe Werkzeuge
          Files and Folders : Dateien und Ordner
          Finding courses : Kurse finden
          Form editor (Questionnaire editor) : Formular Editor
          Forms in Courses : Formulare in Kursen
          Forms in Forms Element : Formular in Formularen
          Forms in Questionnaires : Formular in Umfragen
          Forms in Rubric Scoring : Formular als Rubrik Bewertung
          Forms in the ePortfolio template : Formular in der Portfolio 2.0 Vorlage
          Four Steps to Your Blog : Vier Schritte zu Ihrem Blog
          Four Steps to Your Podcast : Vier Schritte zu Ihrem Podcast
          Four Steps to Your Test or Self-test : Vier Schritte zu Ihrem Test oder Selbsttest
          Four Steps to Your Wiki : Vier Schritte zu Ihrem Wiki
          Full-Text Search : Volltextsuche
          General Configuration of Course Elements : Allgemeine Konfiguration von Kursbausteinen
          General Information : Allgemeines
          General information on Forms : Allgemeines zu Formularen
          General Information on Tests : Allgemeines zu Tests
          Group Administration : Gruppenadministration
          Group Management : Gruppenverwaltung
          Groups : Gruppen
          Guest access : Gastzugang
          Guest and invitation : Gast und Einladung
          Häufig gestellte Fragen  : Häufig gestellte Fragen
          How-to... : How-to...
          Imprint: Impressum
          In Five Steps to Your Content Package : Fünf Schritte zu Ihrem Content-Packaging
          In Five Steps to Your Course With the Course Editor : Mit dem Kurseditor in fünf Schritten zu Ihrem OpenOlat-Kurs
          Info page : Infoseite
          Information on OpenOlat : Informationen zu OpenOlat
          Instant Messaging : Instant Messaging
          Introduction : Einführung
          Item Detailed View : Detailansicht einer Frage
          Just a Few Clicks and the Course Wizard Will Create Your OpenOlat Course : Mit dem Kursassistenten in wenigen Mausklicks zu Ihrem OpenOlat-Kurs
          Knowledge Transfer : Wissensvermittlung
          Landing pages : Startseite
          Learning Activities in Courses : Lernaktivitäten im Kurs
          Learning resource Video : Lernressource Video
          Lebenszyklen  : Lebenszyklen
          Lectures and absences : Lektionen und Absenzen
          Lektionen  : Lektionen
          Lektionen  : Lektionen
          Lektionen : Lektionen
          Lernpfad Kurs  : Lernpfad Kurs
          Lernpfad Kurs  : Lernpfad Kurs
          Lernpfad Kurse  : Lernpfad Kurse
          License: Lizenz
          Licenses : Lizenzen
          Login : Login
          Login Page : Login-Seite
          Managing Topics of Topic Assignments : Themen einer Themenvergabe verwalten
          Math formula : Mathematische Formel
          Media center : Mediathek
          Members management : Mitgliederverwaltung
          Modules : Module
          Modules Contact Tracing : Modul Kontaktverfolgung
          Modules Curriculum : Modul Curriculum
          Modules Document pool : Modules Dokumentenpool
          Modules Organisations : Modules Organisationen
          Modules Taxonomy : Modules Taxonomie
          Multiple use of entries : Mehrfachverwendung von Einträgen
          My entries : Meine Einträge
          My portfolio binders : Meine Portfolio Mappen
          Other : Andere
          Overview: Übersicht
          Payment modules : Bezahlungsmodule
          PayPal Configuration : PayPal Konfiguration
          Performance assessment : Leistungsbewertung
          Personal folders : Persönliche Ordner
          Personal Menu : Persönliche Werkzeuge
          Podcast  : Podcast
          Portal configuration : Portal konfigurieren
          Portfolio - General Information : Allgemeines zum Portfolio
          Portfolio assignment Grading : Portfolioaufgabe kommentieren und bewerten
          Portfolio task and assignment Collecting and editing : Portfolioaufgabe abholen und bearbeiten
          Portfolio template Administration and editing : Portfoliovorlage Administration und Bearbeitung
          Portfolio template Creation : Portfoliovorlage Erstellung
          Process of an assessment portfolio : Prozess eines Bewertungsportfolios
          Question Bank : Fragenpool
          Question Bank Administration : Fragenpool Administration
          Question bank possible operations : Mögliche Aktionen im Fragenpool
          Question Bank Review Process : Fragenpool Beurteilungsprozess
          Question Pool Sharing Options : Fragenpool Freigabemöglichkeiten
          Question rules : Frageregeln
          Record of Course Activities : Aufzeichnung der Kursaktivitäten
          Registration, Login and Logout : Registrierung, Login und Logout
          Release notes: Release Notes
          Reports : Reports
          Requirements when Working with OpenOlat : Voraussetzungen für die Arbeit mit OpenOlat
          REST API : REST API
          Roles and Rights : Rollen und Rechte
          Rubric : Rubrik
          Search : Suchfunktion
          Security : Sicherheit
          Session Timeout and Logout : Session-Timeout und Logout
          Set up info page : Infoseite einrichten
          Shared by me : Von mir freigegeben
          Shared with me : An mich freigegeben
          Single Page_Add_edit video : Einzelne Seite_Video hinzufügen_editieren
          Start: Start
          Storage folder : Ablageordner
          Supported Technologies : Unterstützende Technologien
          System : System
          Tab Users : Tab Übersicht
          Technical Information on Resources and Usage : Automatische Informationen zur Lernressource
          Technology and Navigation : Technologie und Navigation
          Test editor QTI 2.1 : Testeditor
          Test question types : Test Fragetypen
          Test settings : Test Einstellungen
          Tests at course level : Tests auf Kursebene
          The assessment form : Das Bewertungsformular
          The Idea of Open-Source Software : Der Open-Source-Gedanke
          The portfolio editor : Der Portfolio Editor
          Three Steps to Create and Manage Topics : Drei Schritte zur Erstellung und Verwaltung von Themen
          Three Steps to your Form : Drei Schritte zu Ihrem Formular
          Three steps to your portfolio binder : Drei Schritte zu Ihrer Mappe
          Three Steps to Your Task : Drei Schritte zu Ihrer Aufgabe
          Types of Course Element : Kursbausteine
          User management : Benutzerverwaltung
          User manual: Benutzerhandbuch
          Using additional Course Editor Tools : Verwendung weiterer Kurseditorwerkzeuge
          Using Additional Course Features : Einsatz weiterer Kursfunktionen der Toolbar
          Using Course Tools : Einsatz der Kurswerkzeuge
          Using Group Tools : Gruppenwerkzeuge nutzen
          Using WebDAV : Einsatz von WebDAV
          Various Types of Learning Resources : Verschiedene Typen von Lernressourcen
          Video Upload : Video hochladen
          Virtual classrooms : Virtuelle Klassenzimmer
          WebDAV : WebDAV
          Working With Course Elements : Arbeiten mit Kursbausteinen
          Working with tables : mit Tabellen arbeiten
          Working with Tasks and Group Tasks : Arbeiten mit Foren
          Working with Tests : Arbeiten mit der Themenvergabe
          Working with Topic Assignment : Arbeiten mit Tests
          Working with Wiki : Arbeiten mit Wiki
          ...create a bulk assessment for submission tasks : ...eine Massenbewertung für Einsendeaufgaben erstellen
          ...customize the course design with CSS (Expert) : ...Kursdesign mittels CSS manipulieren (Expert)
          ...use the same files in several courses : ...dieselben Dateien in mehreren Kursen einsetzen
          

nav:
  - Start: 
    - Overview: index.md
    - Imprint: imprint.md
    - License: license.md
  - Release notes: '!include ./sites/release_notes/mkdocs.yml'
  - User manual: '!include ./sites/manual_user/mkdocs.yml' 
  - Admin manual: '!include ./sites/manual_admin/mkdocs.yml' 
  - Developer cookbook: '!include ./sites/manual_dev/mkdocs.yml' 

