site_name: manual_how-to

nav:
  - index.md
  - Set up OpenOlat:
    - How to customize the course design with CSS: "css/css.md"
  - Working processes:
    - How to use the same files in several courses: "multiple_use/multiple_use.md"
    - How to transfer files using WebDAV: "webdav/how_to_transfer_files_using_webdav.md"
  - Create courses:
    - How to create my first course: "my_first_course/how_to_create_my_first_course.md"
  - Create learning resources:
    - How do I create a blog?: "wikis/Four_Steps_to_Your_Blog.md"
    - How do I create a podcast?: "wikis/Four_Steps_to_Your_Podcast.md"
    - How do I create a wiki?: "wikis/Four_Steps_to_Your_Wiki.md"
  - Offer courses:
    - How can I have my courses found by search engines: "oai_pmh/how_can_I_have_my_courses_found_by_search_engines.md"
  - Attend participants:
    - How and where can I do a bulk assessment: "bulk_assessment/how_to_create_a_bulk_assessment.md"