site_name: manual_how-to

nav:
  - index.md
  - Working Processes:
    - How to use the same files in several courses: "multiple_use/multiple_use.md"
    - Transfer files using WebDAV: "webdav/webdav.md"
  - Create Courses:
    - My first course: "my_first_course/my_first_course.md"
    - How do I use course element "selection"?: "course_element_selection/course_element_selection.md"
  - Create Learning Resources:
    - Create a blog: "blog/blog.md"
    - Create a Content Package: "content_package/content_package.md"
    - Create a form: "create_a_form/create_a_form.md"
    - Create a podcast: "podcast/podcast.md"
    - Create a wiki: "wikis/wikis.md"  
  - Offer Courses:
    - How do I present my courses in the catalog?: "catalog/catalog.md"
    - How can I have my courses found by search engines?: "oai_pmh/oai_pmh.md"
  - Participant Administration:
    - Group Scenarios: "purpose_of_groups/purpose_of_groups.md"
  - Attend Participants:
    - Bulk assessment: "bulk_assessment/bulk_assessment.md"
  - Tests and Assessments:
    - How do I proceed when I create a test?: "test_creation_procedure/test_creation_procedure.md"
    - How do I assess a test?: "assessing_tests/assessing_tests.md"
    - How do I perform a peer review?: "peer_review/peer_review.md"
    - Communication during an exam: "communication_during_exam/communication_during_exam.md"
  - Adjust OpenOlat:
    - Reduce storage consumption: "reduce_storage_consumption/reduce_storage_consumption.md"
    - Lifecycle management: "lifecycle/lifecycle.md"
    - How to customize the course design with CSS: "css/css.md"
    - How do I use the language adaption tool?: "language_adaption_tool/language_adaption_tool.md"