site_name: User Manual

nav:
  - Introduction:
    - general/index.md
    - Information on OpenOlat: "general/Information_on_OpenOlat.md"
    - Requirements when Working with OpenOlat: "general/Requirements_when_Working_with_OpenOlat.md"
    - The Idea of Open-Source Software: "general/The_Idea_of_Open-Source_Software.md"
    - Technology and Navigation: "general/Technology_and_Navigation.md"
    - Roles and Rights: "general/Roles_and_Rights.md"
    - Coach: "general/Coach.md"
    - Guest access: "general/Guest_access.md"

  - Registration, Login and Logout:
    - login/index.md
    - Login Page: "login/Login_Page.md"
    - Session Timeout and Logout: "login/Session_Timeout_and_Logout.md"

  - Personal menu and general components: 
    - personal/index.md
    - Personal Menu: 
      - Overview: "personal/Personal_Menu.md"
      - Calendar: "personal/Calendar.md"
      - Personal folders: "personal/Personal_folders.md"
      - E-Mail: "personal/E-Mail.md"
    - Configuration: 
      - Overview: "personal/Configuration.md"
      - COVID certificate: "personal/COVID_certificate.md"
    - Full-Text Search: "personal/Full-Text_Search.md"
    - Chat: "personal/Chat.md"
    - Portal configuration: "personal/Portal_configuration.md"
    - Math formula: "personal/Math_formula.md"
    - Working with tables: "personal/Working_with_tables.md"

  - Groups:
    - groups/index.md
    - Create Groups: "groups/Create_Groups.md"
    - Group Administration: "groups/Group_Administration.md"
    - Using Group Tools: "groups/Using_Group_Tools.md"
    - Group Management: "groups/Group_Management.md"
    
  - Courses and Catalog: 
    - catalog/index.md
    - Finding courses: "catalog/Finding_courses.md"
    - Info page: "catalog/Info_page.md"

  - Learning Activities in Courses: 
    - learning_activities/index.md
    - Working With Course Elements: 
      - Overview: "learning_activities/Working_With_Course_Elements.md"
      - Working with Tasks and Group Tasks: "learning_activities/Working_with_Tasks_and_Group_Tasks.md"
      - Working with Tests: "learning_activities/Working_with_Tests.md"
      - Working with Topic Assignment: "learning_activities/Working_with_Topic_Assignment.md"
      - Working with Wiki: "learning_activities/Working_with_Wiki.md"
    - Additional Course Features: "learning_activities/Additional_Course_Features.md"
    - Exams: "learning_activities/Exams.md"
    - Course Problems and Error Messages: "learning_activities/Course_Problems_and_Error_Messages.md"
    
  - Authoring: 
    - authoring/index.md
    - Various Types of Learning Resources: "authoring/Various_Types_of_Learning_Resources.md"
    - Actions in the Authoring section: "authoring/Actions_in_the_'Authoring'_section.md"
    - Detailed View of Learning Resources: "authoring/Detailed_View_of_Learning_Resources.md"
    - Set up info page: "authoring/Set_up_info_page.md"
    - Technical Information on Resources and Usage: "authoring/Technical_Information_on_Resources_and_Usage.md"
    
  - Creating Courses: 
    - course_create/index.md
    - General Information: "course_create/General_Information.md"
    - In Five Steps to Your Course With the Course Editor: "course_create/In_Five_Steps_to_Your_Course_With_the_Course_Editor.md"
    - Just a Few Clicks and the Course Wizard Will Create Your OpenOlat Course: "course_create/Just_a_Few_Clicks_and_the_Course_Wizard_Will_Create_Your_OpenOlat_Course.md"
    - Lernpfad Kurs : 
      - Overview : "course_create/Learning_path_course.md"
      - Creating learning path courses: "course_create/Creating_learning_path_courses.md"
      - Lernpfad Kurs : "course_create/Learning_path_course_-_Course_editor.md"
      - Lernpfad Kurse : "course_create/Learning_path_course_-_Participant_view.md"
    - General Configuration of Course Elements:
      - Overview: "course_create/General_Configuration_of_Course_Elements.md"
      - Deleting, Moving and Copying Course Elements: "course_create/Deleting_Moving_and_Copying_Course_Elements.md"
      - Access Restrictions in the Expert Mode: "course_create/Access_Restrictions_in_the_Expert_Mode.md"
    - Using additional Course Editor Tools: "course_create/Using_additional_Course_Editor_Tools.md"
    - Course Settings:
      - Overview: "course_create/Course_Settings.md"
      - Design possibilities of courses and course elements: "course_create/Design_possibilities_of_courses_and_course_elements.md"
    - Access configuration: "course_create/Access_configuration.md"
    
  - Types of Course Element: 
    - course_elements/index.md
    - Knowledge Transfer:
      - Overview: "course_elements/Knowledge_Transfer.md"
      - Course Element Structure: "course_elements/Course_Element_Structure.md"
      - Course Element Folder: "course_elements/Course_Element_Folder.md"
      - Course Element Single Page: "course_elements/Course_Element_Single_Page.md"
      - Course Element SCORM Learning Content: "course_elements/Course_Element_SCORM_Learning_Content.md"
      - Course Element card2brain Flashcards: "course_elements/Course_Element_card2brain_Flashcards.md"
      - Course Element Mediasite: "course_elements/Course_Element_Mediasite.md"
    - Assessment: 
      - Overview: "course_elements/Assessment.md"
      - Course Element Assessment: "course_elements/Course_Element_Assessment.md"
      - Course Element Checklist: "course_elements/Course_Element_Checklist.md"
    - Communication and Collaboration:
      - Overview: "course_elements/Communication_and_Collaboration.md"
      - Virtual classrooms: "course_elements/Virtual_classrooms.md"
      - Course element Adobe Connect: "course_elements/Course_element_Adobe_Connect.md"
      - Course element BigBlueButton: "course_elements/Course_element_BigBlueButton.md"
      - BBB - Frequently asked questions : "course_elements/Frequentyl_asked_questions_-_BigBlueButton.md"
      - Course element GoToMeeting: "course_elements/Course_element_GoToMeeting.md"
      - Course element OpenMeetings: "course_elements/Course_element_OpenMeetings.md"
      - Course element vitero: "course_elements/Course_element_vitero.md"
      - Course element Microsoft Teams: "course_elements/Course_element_Microsoft_Teams.md"
    - Administration and Organisation: "course_elements/Administration_and_Organisation.md"
    - Other: "course_elements/Other.md"

  - Course Operation: 
    - course_operation/index.md
    - Using Course Tools:
      - Overview: "course_operation/Using_Course_Tools.md"
      - Members management: "course_operation/Members_management.md"
      - Storage folder: "course_operation/Storage_folder.md"
      - Assessment tool :
        - Overview : "course_operation/Assessment_tool_-_overview.md"
        - Tab users: "course_operation/Assessment_tool_-_tab_Users.md"
        - Assessment of learners: "course_operation/Assessment_of_learners.md"
        - Assessment of course modules: "course_operation/Assessment_of_course_modules.md"
        - Assessing tasks and group tasks: "course_operation/Assessing_tasks_and_group_tasks.md"
        - Assessing tests: "course_operation/Assessing_tests.md"
        - The assessment form: "course_operation/The_assessment_form.md"
      - Lectures and absences:
        - Overview: "course_operation/Lectures_and_absences.md"
        - Lektionen : "course_operation/Lectures_-_User_view.md"
        - Lektionen : "course_operation/Lectures_-_Teacher_view.md"
      - Course Reminders: "course_operation/Course_Reminders.md"
      - Data archiving: "course_operation/Data_archiving.md"
      - Record of Course Activities: "course_operation/Record_of_Course_Activities.md"
    - Using Additional Course Features: "course_operation/Using_Additional_Course_Features.md"

  - How-to ...: 
    - how-to/index.md
    - ... create a bulk assessment for submission tasks: "how-to/create_a_bulk_assessment_for_submission_tasks.md"
    - ... customize the course design with CSS (Expert): "how-to/customize_the_course_design_with_CSS_Expert.md"
    - ... use the same files in several courses: "how-to/use_the_same_files_in_several_courses.md"

  - eAssessment: 
    - e-assessment/index.md
    - Assessment mode: "e-assessment/Assessment_mode.md"
    - Performance assessment: "e-assessment/Performance_assessment.md"
    - Coaching: "e-assessment/Coaching.md"
    
  - Creating CP Learning Content: 
    - resource_cp/index.md
    - In Five Steps to Your Content Package: "resource_cp/In_Five_Steps_to_Your_Content_Package.md"
    - CP Editor: "resource_cp/CP_Editor.md"
    
  - Creating Wikis:
    - resource_wiki/index.md
    - Four Steps to Your Wiki: "resource_wiki/Four_Steps_to_Your_Wiki.md"
    
  - Creating Videos:
    - resource_video/index.md
    - Learning resource Video: "resource_video/Learning_resource_Video.md"
    - Course Element_Video: "resource_video/Course_Element_Video.md"
    - Single Page_Add_edit video: "resource_video/Single_Page_Add_edit_video.md"
    - Video Upload: "resource_video/Video_Upload.md"

  - Creating Podcasts:
    - resource_podcast/index.md
    - Four Steps to Your Podcast: "resource_podcast/Four_Steps_to_Your_Podcast.md"
    - Podcast : "resource_podcast/Podcast_-_Further_Configurations.md"

  - Creating Blogs:
    - resource_blog/index.md
    - Four Steps to Your Blog: "resource_blog/Four_Steps_to_Your_Blog.md"
    - Blog : "resource_blog/Blog_-_Further_Configurations.md"

  - Creating Tasks:
    - task/index.md
    - Three Steps to Your Task: "task/Three_Steps_to_Your_Task.md"
    - Aufgabe : "task/Task_-_Further_Configurations.md"
    - Assess tasks: "task/Assess_tasks.md"

  - Creating Portfolios:
    - portfolio/index.md
    - Portfolio - General Information: "portfolio/Portfolio_-_General_Information.md"
    - Components of the portfolio: 
      - Overview: "portfolio/Components_of_the_portfolio.md"
      - My portfolio binders: "portfolio/My_portfolio_binders.md"
      - My entries: "portfolio/My_entries.md"
      - Media center: "portfolio/Media_center.md"
      - Shared by me: "portfolio/Shared_by_me.md"
      - Shared with me: "portfolio/Shared_with_me.md"
    - Three steps to your portfolio binder: "portfolio/Three_steps_to_your_portfolio_binder.md"
    - The portfolio editor: "portfolio/The_portfolio_editor.md"
    - Multiple use of entries: "portfolio/Multiple_use_of_entries.md"
    - Competences tags: "portfolio/Competences_tags.md"
    - Process of an assessment portfolio: 
      - Overview: "portfolio/Process_of_an_assessment_portfolio.md"
      - Portfolio template Creation: "portfolio/Portfolio_template_Creation.md"
      - Portfolio template Administration and editing: "portfolio/Portfolio_template_Administration_and_editing.md"
      - Creating Portfolio Tasks: "portfolio/Creating_Portfolio_Tasks.md"
      - Portfolio task and assignment Collecting and editing: "portfolio/Portfolio_task_and_assignment_Collecting_and_editing.md"
      - Portfolio assignment Grading: "portfolio/Portfolio_assignment_Grading.md"

  - Managing Topics of Topic Assignments:
    - topic_assignment/index.md
    - Three Steps to Create and Manage Topics: "topic_assignment/Three_Steps_to_Create_and_Manage_Topics.md"
    
  - Creating Forms:
    - forms/index.md
    - General information on Forms: "forms/General_information_on_Forms.md"
    - Three Steps to your Form: "forms/Three_Steps_to_your_Form.md"
    - Form editor (Questionnaire editor): 
      - Overview: "forms/Form_editor_Questionnaire_editor.md"
      - Rubric: "forms/Rubric.md"
      - Question rules: "forms/Question_rules.md"
    - Forms in Courses: 
      - Overview: "forms/Forms_in_Courses.md"
      - Forms in Forms Element: "forms/Forms_in_Forms_Element.md"
      - Forms in Questionnaires: "forms/Forms_in_Questionnaires.md"
      - Forms in Rubric Scoring: "forms/Forms_in_Rubric_Scoring.md"
      - Forms in the ePortfolio template: "forms/Forms_in_the_ePortfolio_template.md"
    
  - Creating Tests:
    - tests/index.md
    - General Information on Tests: "tests/General_Information_on_Tests.md"
    - Four Steps to Your Test or Self-test: "tests/Four_Steps_to_Your_Test_or_Self-test.md"
    - Test editor QTI 2.1: 
      - Overview: "tests/Test_editor_QTI_2.1.md"
      - Test question types: "tests/Test_question_types.md"
      - Configure test questions: "tests/Configure_test_questions.md"
      - Configure tests: "tests/Configure_tests.md"
    - Test settings: "tests/Test_settings.md"
    - Tests at course level: "tests/Tests_at_course_level.md"
    
  - Question Bank:
    - question_bank/index.md
    - Data Management: "question_bank/Data_Management.md"
    - Item Detailed View: "question_bank/Item_Detailed_View.md"
    - Question bank possible operations: "question_bank/Question_bank_possible_operations.md"
    - Search: "question_bank/Search.md"
    - Question Pool Sharing Options: "question_bank/Question_Pool_Sharing_Options.md"
    - Question Bank Review Process: "question_bank/Question_Bank_Review_Process.md"
    - Question Bank Administration: "question_bank/Question_Bank_Administration.md"

  - Curriculum Management: "curriculum/Curriculum_Management.md"
    
  - Supported Technologies: 
    - supported_tech/index.md 
    - Using WebDAV: "supported_tech/Using_WebDAV.md"
    
    