site_name: User Manual

nav:
  - Introduction:
    - general/index.md
    - Information on OpenOlat: "general/Information_on_OpenOlat.md"
    - Requirements when Working with OpenOlat: "general/Requirements_when_Working_with_OpenOlat.md"
    - The Idea of Open-Source Software: "general/The_Idea_of_Open-Source_Software.md"
    - Technology and Navigation: "general/Technology_and_Navigation.md"
    - Roles and Rights: "general/Roles_and_Rights.md"
    - Coach: "general/Coach.md"
    - Guest access: "general/Guest_access.md"

  - Registration, Login and Logout:
    - login/index.md
    - Login Page: "login/Login_Page.md"
    - Session Timeout and Logout: "login/Session_Timeout_and_Logout.md"

  - Personal menu and general components: 
    - personal/index.md
    - Personal Menu: 
      - Personal Menu: "personal/Personal_Menu.md"
      - Calendar: "personal/Calendar.md"
      - Personal folders: "personal/Personal_folders.md"
      - E-Mail: "personal/E-Mail.md"
    - Configuration: 
      - Configuration: "personal/Configuration.md"
      - COVID certificate: "personal/COVID_certificate.md"
    - Full-Text Search: "personal/Full-Text_Search.md"
    - Chat: "personal/Chat.md"
    - Portal configuration: "personal/Portal_configuration.md"
    - Math formula: "personal/Math_formula.md"
    - Working with tables: "personal/Working_with_tables.md"

  - Groups:
    - groups/index.md
    - Create Groups: "groups/Create_Groups.md"
    - Group Administration: "groups/Group_Administration.md"
    - Using Group Tools: "groups/Using_Group_Tools.md"
    - Group Management: "groups/Group_Management.md"
    
  - Courses and Catalog: 
    - catalog/index.md
    - Finding courses: "catalog/Finding_courses.md"
    - Info page: "catalog/Info_page.md"

  - Learning Activities in Courses: 
    - "learning_activities/index.md"
    - Working With Course Elements: 
      - Working With Course Elements: "learning_activities/Working_With_Course_Elements.md"
      - Working with Tasks and Group Tasks: "learning_activities/Working_with_Tasks_and_Group_Tasks.md"
      - Working with Tests: "learning_activities/Working_with_Tests.md"
      - Working with Topic Assignment: "learning_activities/Working_with_Topic_Assignment.md"
      - Working with Wiki: "learning_activities/Working_with_Wiki.md"
    - Additional Course Features: "learning_activities/Additional_Course_Features.md"
    - Exams: "learning_activities/Exams.md"
    - Course Problems and Error Messages: "learning_activities/Course_Problems_and_Error_Messages.md"
    
  - Authoring: 
    - authoring/index.md
    - Various Types of Learning Resources: "authoring/Various_Types_of_Learning_Resources.md"
    - Actions in the Authoring section: "authoring/Actions_in_the_'Authoring'_section.md"
    - Detailed View of Learning Resources: "authoring/Detailed_View_of_Learning_Resources.md"
    - Set up info page: "authoring/Set_up_info_page.md"
    - Technical Information on Resources and Usage: "authoring/Technical_Information_on_Resources_and_Usage.md"
