site_name: User Manual

nav:
  - Introduction:
    - general/index.md
    - Information on OpenOlat: "general/Information_on_OpenOlat.md"
    - Requirements when Working with OpenOlat: "general/Requirements_when_Working_with_OpenOlat.md"
    - The Idea of Open-Source Software: "general/The_Idea_of_Open-Source_Software.md"
    - Technology and Navigation: "general/Technology_and_Navigation.md"
    - Roles and Rights: "general/Roles_and_Rights.md"
    - Coach: "general/Coach.md"
    - Guest access: "general/Guest_access.md"

  - Registration, Login and Logout:
    - login/index.md
    - Login Page: "login/Login_Page.md"
    - Session Timeout and Logout: "login/Session_Timeout_and_Logout.md"

  
