site_name: User Manual

nav:
  - Introduction:
    - general/index.md
    - Information on OpenOlat: "general/Information_on_OpenOlat.md"
    - Requirements when Working with OpenOlat: "general/Requirements_when_Working_with_OpenOlat.md"
    - The Idea of Open-Source Software: "general/The_Idea_of_Open-Source_Software.md"
    - Technology and Navigation: "general/Technology_and_Navigation.md"
    - Roles and Rights: "general/Roles_and_Rights.md"
    - Coach: "general/Coach.md"
    - Guest access: "general/Guest_access.md"

  - Registration, Login and Logout:
    - login/index.md
    - Login Page: "login/Login_Page.md"
    - Session Timeout and Logout: "login/Session_Timeout_and_Logout.md"

  - Personal menu and general components: 
    - personal/index.md
    - Personal Menu: 
      - Personal Menu: "personal/Personal_Menu.md"
      - Calendar: "personal/Calendar.md"
      - Personal folders: "personal/Personal_folders.md"
      - E-Mail: "personal/E-Mail.md"
    - Configuration: 
      - Configuration: "personal/Configuration.md"
      - COVID certificate: "personal/COVID_certificate.md"
    - Full-Text Search: "personal/Full-Text_Search.md"
    - Chat: "personal/Chat.md"
    - Portal configuration: "personal/Portal_configuration.md"
    - Math formula: "personal/Math_formula.md"
    - Working with tables: "personal/Working_with_tables.md"

  - Groups:
    - groups/index.md
    - Create Groups: "groups/Create_Groups.md"
    - Group Administration: "groups/Group_Administration.md"
    - Using Group Tools: "groups/Using_Group_Tools.md"
    - Group Management: "groups/Group_Management.md"
    
  - Courses and Catalog: 
    - catalog/index.md
    - Finding courses: "catalog/Finding_courses.md"
    - Info page: "catalog/Info_page.md"

  - Learning Activities in Courses: 
    - "learning_activities/index.md"
    - Working With Course Elements: 
      - Working With Course Elements: "learning_activities/Working_With_Course_Elements.md"
      - Working with Tasks and Group Tasks: "learning_activities/Working_with_Tasks_and_Group_Tasks.md"
      - Working with Tests: "learning_activities/Working_with_Tests.md"
      - Working with Topic Assignment: "learning_activities/Working_with_Topic_Assignment.md"
      - Working with Wiki: "learning_activities/Working_with_Wiki.md"
    - Additional Course Features: "learning_activities/Additional_Course_Features.md"
    - Exams: "learning_activities/Exams.md"
    - Course Problems and Error Messages: "learning_activities/Course_Problems_and_Error_Messages.md"
    
  - Authoring: 
    - authoring/index.md
    - Various Types of Learning Resources: "authoring/Various_Types_of_Learning_Resources.md"
    - Actions in the Authoring section: "authoring/Actions_in_the_'Authoring'_section.md"
    - Detailed View of Learning Resources: "authoring/Detailed_View_of_Learning_Resources.md"
    - Set up info page: "authoring/Set_up_info_page.md"
    - Technical Information on Resources and Usage: "authoring/Technical_Information_on_Resources_and_Usage.md"
    
  - Creating Courses: 
    - course_create/index.md
    - General Information: "course_create/General_Information.md"
    - In Five Steps to Your Course With the Course Editor: "course_create/In_Five_Steps_to_Your_Course_With_the_Course_Editor.md"
    - Just a Few Clicks and the Course Wizard Will Create Your OpenOlat Course: "course_create/Just_a_Few_Clicks_and_the_Course_Wizard_Will_Create_Your_OpenOlat_Course.md"
    - Lernpfad Kurs : 
      - Lernpfad Kurs : "course_create/Learning_path_course.md"
      - Creating learning path courses: "course_create/Creating_learning_path_courses.md"
      - Lernpfad Kurs : "course_create/Learning_path_course_-_Course_editor.md"
      - Lernpfad Kurse : "course_create/Learning_path_course_-_Participant_view.md"
    - General Configuration of Course Elements:
      - General Configuration of Course Elements: "course_create/General_Configuration_of_Course_Elements.md"
      - Deleting, Moving and Copying Course Elements: "course_create/Deleting_Moving_and_Copying_Course_Elements.md"
      - Access Restrictions in the Expert Mode: "course_create/Access_Restrictions_in_the_Expert_Mode.md"
    - Using additional Course Editor Tools: "course_create/Using_additional_Course_Editor_Tools.md"
    - Course Settings:
      - Course Settings: "course_create/Course_Settings.md"
      - Design possibilities of courses and course elements: "course_create/Design_possibilities_of_courses_and_course_elements.md"
    - Access configuration: "course_create/Access_configuration.md"
    
  - Types of Course Element: 
    - "course_elements/index.md"
    - Knowledge Transfer:
      - Knowledge Transfer: "course_elements/Knowledge_Transfer.md"
      - Course Element Structure: "course_elements/Course_Element_Structure.md"
      - Course Element Folder: "course_elements/Course_Element_Folder.md"
      - Course Element Single Page: "course_elements/Course_Element_Single_Page.md"
      - Course Element SCORM Learning Content: "course_elements/Course_Element_SCORM_Learning_Content.md"
      - Course Element card2brain Flashcards: "course_elements/Course_Element_card2brain_Flashcards.md"
      - Course Element Mediasite: "course_elements/Course_Element_Mediasite.md"
      - Course Element Video: "course_elements/Course_Element_Video.md"
    - Assessment: 
      - Assessment: "course_elements/Assessment.md"
      - Course Element Assessment: "course_elements/Course_Element_Assessment.md"
      - Course Element Checklist: "course_elements/Course_Element_Checklist.md"
    - Communication and Collaboration:
      - Communication and Collaboration: "course_elements/Communication_and_Collaboration.md"
      - Virtual classrooms: "course_elements/Virtual_classrooms.md"
      - Course element Adobe Connect: "course_elements/Course_element_Adobe_Connect.md"
      - Course element BigBlueButton: "course_elements/Course_element_BigBlueButton.md"
      - BBB - Frequently asked questions : "course_elements/Frequentyl_asked_questions_-_BigBlueButton.md"
      - Course element GoToMeeting: "course_elements/Course_element_GoToMeeting.md"
      - Course element OpenMeetings: "course_elements/Course_element_OpenMeetings.md"
      - Course element vitero: "course_elements/Course_element_vitero.md"
      - Course element Microsoft Teams: "course_elements/Course_element_Microsoft_Teams.md"
    - Administration and Organisation: "course_elements/Administration_and_Organisation.md"
    - Other: "course_elements/Other.md"



    
