site_name: manual_user

nav:
  - general/index.md
  - Basic concepts:
    - basic_concepts/index.md
    - Requirements: "basic_concepts/Requirements_OpenOlat.md"
    - Roles and Rights:
      - basic_concepts/Roles_Rights.md
      - Authorisation concept: "basic_concepts/Authorisation_Concept.md"
      - Coach: "basic_concepts/coach.md"
      - Guest access: "basic_concepts/guest_access.md"
    - Account:
      - Session Timeout and Logout: "basic_concepts/Session_Timeout_and_Logout.md"  
    - Framework:
      - Navigation: "basic_concepts/Navigation.md"
      - Full-Text Search: "basic_concepts/Full_Text_Search.md"
      - Portal configuration: "basic_concepts/Portal_configuration.md"
      - Chat: "basic_concepts/Chat.md"
      - Table concept: "basic_concepts/Table_Concept.md"
      - Math formula: "basic_concepts/Math_formula.md"
      - To-dos: "basic_concepts/To_Dos_Basics.md"
    - Technology:
      - basic_concepts/Technology.md 
      - Using WebDAV: "basic_concepts/Using_WebDAV.md" 
      - Technology and Navigation: "basic_concepts/Technology_and_Navigation.md"
 
  - Login and registration:
    - login_registration/index.md
    - Login Page: "login_registration/Login_Page.md"
    - Login Concept: "login_registration/Login_Concept.md"
    - Password: "login_registration/Password.md"
    - Passkey: "login_registration/Passkey.md"
    - Security levels: "login_registration/Security_levels.md"

  - Personal menu:
    - personal_menu/index.md
    - Personal tools:
      - Calendar: "personal_menu/Calendar.md"
      - Personal folders: "personal_menu/Personal_folders.md"
      - Competences : "personal_menu/Competences.md"
      - E-Mail: "personal_menu/E-Mail.md"
      - Badges: "personal_menu/OpenBadges.md"
      - Media Center: "personal_menu/Media_Center.md"
      - To-dos: "personal_menu/To-Dos.md"
    - Configuration:
      - Profile: "personal_menu/Profile.md"
      - COVID certificate: "personal_menu/COVID_certificate.md"
      - Settings: "personal_menu/Settings.md"
      - Password: "personal_menu/Password.md"
       
  - Area and modules:
    - area_modules/index.md
    - Courses:
      - Overview: "area_modules/Courses.md"
      - Catalog 1.0: "area_modules/catalog1.0.md"
    - Catalog:
      - Overview: "area_modules/catalog2.0.md"
      - Offers: "area_modules/catalog2.0_angebote.md"
    - Groups:
       - Group Management: "area_modules/Group_Management.md"
    - Coaching:
      - Overview: "area_modules/Coaching.md"
      - Lectures: "area_modules/coaching_lektionen.md"
      - Classes: "area_modules/coaching_klassen.md"
      - Members: "area_modules/coaching_teilnehmer.md"
      - Groups: "area_modules/coaching_gruppen.md"
      - Courses: "area_modules/coaching_kurse.md"
      - Role user to user: "area_modules/coaching_personenbeziehungen.md" 
      - Line manager: "area_modules/coaching_linienvorgesetzte.md"
      - Orders: "area_modules/coaching_auftraege.md"
      - Orders management: "area_modules/coaching_auftragsverwaltung.md"
      - User search: "area_modules/coaching_personensuche.md" 
    - Authoring:
       - Overview: "area_modules/Authoring.md"
       - Create courses and learning resources: "area_modules/authoring_new_course.md"
       - Bulk actions: "area_modules/Authoring_BulkActions.md"
    - Question Bank:
      - Overview: "area_modules/Question_Bank.md"
      - Data Management: "area_modules/Data_Management.md"
      - Item Detailed View: "area_modules/Item_Detailed_View.md"
      - Question bank possible operations: "area_modules/Question_bank_possible_operations.md"
      - Search: "area_modules/Search.md"
      - Question Pool Sharing Options: "area_modules/Question_Pool_Sharing_Options.md"
      - Question Bank Review Process: "area_modules/Question_Bank_Review_Process.md"
      - Question Bank Administration: "area_modules/Question_Bank_Administration.md"
    - Projects:
      - Overview: "area_modules/Project_Overview.md"
      - Project member management: "area_modules/Project_Member_Management.md"
      - Cockpit: "area_modules/Project_Cockpit.md"
      - Whiteboard: "area_modules/Project_Whiteboard.md"
      - Timeline: "area_modules/Project_Timeline.md"
      - Schedule: "area_modules/Project_Schedule.md"
      - To-dos: "area_modules/Project_Todos.md"
      - Decisions: "area_modules/Project_Decisions.md"
      - Notes: "area_modules/Project_Notes.md"
      - Files: "area_modules/Project_Files.md"
      - Video/Audio: "area_modules/Project_VideoAudio.md"
      - Administration: "area_modules/Project_Admin.md"
      - Project Report: "area_modules/Project_Report.md"
    - Portfolio:
      - Overview: "area_modules/Portfolio.md"
      - Portfolio - General Information: "area_modules/Portfolio_General_Information.md"
      - Components of the portfolio:
        - Overview: "area_modules/Components_of_the_portfolio.md"
        - My portfolio binders: "area_modules/My_portfolio_binders.md"
        - My entries: "area_modules/My_entries.md"
        - Shared by me: "area_modules/Shared_by_me.md"
        - Shared with me: "area_modules/Shared_with_me.md"
        - Multiple use of entries: "area_modules/Multiple_use_of_entries.md"
        - Competences tags: "area_modules/Competences_tags.md"
        - The portfolio editor: "area_modules/The_portfolio_editor.md"
        - The portfolio editor for 17.1: "area_modules/The_portfolio_editor_17_1.md"
    - Curriculum Management: "area_modules/Curriculum_Management.md"

  - Learning resources:
    - learningresources/index.md
    - General functions:
      - Detailed View of Learning Resources: "learningresources/Detailed_View_of_Learning_Resources.md"
      - Set up info page: "learningresources/Set_up_info_page.md"
      - Technical Information on Resources and Usage: "learningresources/Technical_Information_on_Resources_and_Usage.md"
      - Access configuration: "learningresources/Access_configuration.md"
    - Course:
      - Overview: "learningresources/General_Information.md"
      - Create course: "learningresources/Creating_Course.md"
      - Course design:
        - Overview: "learningresources/Learning_path_course.md"
        - Creating learning path courses: "learningresources/Creating_learning_path_courses.md"
        - Learning path course - Course editor: "learningresources/Learning_path_course_Course_editor.md"
        - Learning path course - Participant view: "learningresources/Learning_path_course_Participant_view.md"
      - Course editor:
        - Overview: "learningresources/General_Configuration_of_Course_Elements.md"
        - Deleting, Moving and Copying Course Elements: "learningresources/Deleting_Moving_and_Copying_Course_Elements.md"
        - Access Restrictions in the Expert Mode: "learningresources/Access_Restrictions_in_the_Expert_Mode.md"
        - Using additional Course Editor Tools: "learningresources/Using_additional_Course_Editor_Tools.md"
      - Toolbar:
        - Info page: "learningresources/Info_page.md"
        - Additional Course Features: "learningresources/Additional_Course_Features.md"
        - Using Additional Course Features: "learningresources/Using_Additional_Course_Features.md"
      - Administration:
        - Overview: "learningresources/Administration.md"
        - Using Course Tools: "learningresources/Using_Course_Tools.md"
        - Members management: "learningresources/Members_management.md"
        - Storage folder: "learningresources/Storage_folder.md"
        - Assessment tool :
          - Overview : "learningresources/Assessment_tool_overview.md"
          - Tab users: "learningresources/Assessment_tool_tab_Users.md"
          - Assessment of learners: "learningresources/Assessment_of_learners.md"
          - Assessment of course modules: "learningresources/Assessment_of_course_modules.md"
          - Assessing tasks and group tasks: "learningresources/Assessing_tasks_and_group_tasks.md"
          - Assessing tests: "learningresources/Assessing_tests.md"
          - The assessment form: "learningresources/The_assessment_form.md"
          - Grading / Evaluation Scale: "learningresources/Assessment_translate_points_in_grades.md"
          - Badges : "learningresources/OpenBadges.md"
          - Assess tasks: "learningresources/Assess_tasks.md"
          - Portfolio assignment Grading: "learningresources/Portfolio_assignment_Grading.md"
          - Forms in Rubric Scoring: "learningresources/Forms_in_Rubric_Scoring.md"
        - Lectures and absences:
          - Overview: "learningresources/Lectures_and_absences.md"
          - Lectures : "learningresources/Lectures_User_view.md"
          - Lectures teacherview : "learningresources/Lectures_Teacher_view.md"
        - Course Reminders: "learningresources/Course_Reminders.md"
        - Data archiving: "learningresources/Data_archiving.md"
        - Record of Course Activities: "learningresources/Record_of_Course_Activities.md"
        - Exams: "learningresources/Exams.md"
        - Assessment mode: "learningresources/Assessment_mode.md"
      - Settings:
        - Overview: "learningresources/Course_Settings.md"
        - LTI access: "learningresources/LTI_Share_courses.md"
        - Design possibilities of courses and course elements: "learningresources/Design_possibilities_of_courses_and_course_elements.md"
    - Course elements: 
      - Overview: "learningresources/Course_Elements.md"
      - Structure: "learningresources/Course_Element_Structure.md"
      - Page: "learningresources/Course_Element_Page.md"
      - HTML Page: "learningresources/Course_Element_HTML_Page.md"
      - External Page: "learningresources/Course_Element_External_Page.md"
      - CP learning content: "learningresources/Course_Element_CP_Learning_Content.md"
      - SCORM Learning Content: "learningresources/Course_Element_SCORM_Learning_Content.md"
      - Document: "learningresources/Course_Element_Document.md"
      - Folder: "learningresources/Course_Element_Folder.md"
      - Podcast: "learningresources/Course_Element_Podcast.md"
      - Blog: "learningresources/Course_Element_Blog.md"
      - Video: "learningresources/Course_Element_Video.md"
      - Video Livestream: "learningresources/Course_Element_Video_Livestream.md"
      - Opencast: "learningresources/Course_Element_Opencast.md"
      - edu-sharing: "learningresources/Course_Element_edu_Sharing.md"
      - card2brain Flashcards: "learningresources/Course_Element_card2brain_Flashcards.md"
      - Mediasite: "learningresources/Course_Element_Mediasite.md"
      - Edubase: "learningresources/Course_Element_Edubase.md"
      - JupyterHub: "learningresources/Course_Element_JupyterHub.md"
      - Assessment: "learningresources/Course_Element_Assessment.md"
      - Task: "learningresources/Course_Element_Task.md"
      - Grouptask: "learningresources/Course_Element_Grouptask.md"
      - Portfolio Task: "learningresources/Course_Element_Portfolio_Task.md"
      - Test: "learningresources/Course_Element_Test.md"
      - Self-test: "learningresources/Course_Element_Self_Test.md"
      - Practice: "learningresources/Course_Element_Practice.md"
      - Video task: "learningresources/Course_Element_Video_Task.md"
      - Form: "learningresources/Course_Element_Form.md"
      - Survey : "learningresources/Course_Element_Survey.md"
      - Checklist: "learningresources/Course_Element_Checklist.md"
      - Wiki: "learningresources/Course_Element_Wiki.md"
      - Forum: "learningresources/Course_Element_Forum.md"
      - File dialog: "learningresources/Course_Element_File_Dialog.md"
      - Participant Folder: "learningresources/Course_Element_Participant_Folder.md"
      - Participant list: "learningresources/Course_Element_Participant_List.md"
      - vitero: "learningresources/Course_Element_vitero.md"
      - OpenMeetings: "learningresources/Course_Element_OpenMeetings.md"
      - Adobe Connect: "learningresources/Course_Element_Adobe_Connect.md"
      - GoToMeeting: "learningresources/Course_Element_GoToMeeting.md"
      - BigBlueButton: "learningresources/Course_Element_BigBlueButton.md"
      - BBB - Frequently asked questions : "learningresources/Frequentyl_asked_questions_BigBlueButton.md"
      - Microsoft Teams: "learningresources/Course_Element_Microsoft_Teams.md"
      - Zoom: "learningresources/Course_Element_Zoom.md"
      - Zoom - Frequently asked questions : "learningresources/Frequentyl_asked_questions_Zoom.md"
      - Enrolment: "learningresources/Course_Element_Enrolment.md"
      - Notifications: "learningresources/Course_Element_Notifications.md"
      - E-Mail: "learningresources/Course_Element_EMail.md"
      - Calendar: "learningresources/Course_Element_Calendar.md"
      - Appointment scheduling: "learningresources/Course_Element_Appointment_Scheduling.md"
      - LTI Page: "learningresources/Course_Element_LTI_Page.md"
      - Topic assigment: "learningresources/Course_Element_Topic_Assignment.md"
      - Link list: "learningresources/Course_Element_Link_List.md"
    - Test:
      - Overview: "learningresources/Test.md"
      - General Information on Tests: "learningresources/General_Information_on_Tests.md"
      - Test editor QTI 2.1: 
        - Overview: "learningresources/Test_editor_QTI_2.1.md"
        - Test question types: "learningresources/Test_question_types.md"
        - Configure test questions: "learningresources/Configure_test_questions.md"
        - Configure tests: "learningresources/Configure_tests.md"
        - Test settings: "learningresources/Test_settings.md"
      - Changing from QTI 1.2 to QTI 2.1: "learningresources/Changing_from_QTI_1.2_to_QTI_2.1.md"
    - CP learning content:
       - CP Editor: "learningresources/CP_Editor.md"
    - Wiki:
      - Overview: "learningresources/Wiki.md"
    - Podcast:
      - Overview: "learningresources/Podcast.md"
      - Podcast: "learningresources/Podcast_Further_Configurations.md"
    - Blog:
       - Overview: "learningresources/Blog.md"
       - Blog: "learningresources/Blog_Further_Configurations.md"
    - Audio:
      - Audio Recording: "learningresources/Audio_Recording.md" 
    - Video:
      - Overview: "learningresources/Video.md"
      - Video in HTML Pages: "learningresources/Video_in_HTML_Pages.md"
      - Learning resource Video: "learningresources/Learning_resource_Video.md"
      - Video Upload: "learningresources/Video_Upload.md"
      - Video Recording: "learningresources/Video_Recording.md"
    - Resource folder:
      - Overview: "learningresources/Resource_Folder.md"
    - Form:
      - Overview: "learningresources/Form.md"
      - Forms in Courses: "learningresources/Forms_in_Courses.md"
      - General information on Forms: "learningresources/General_information_on_Forms.md"
      - Form editor (Questionnaire editor): 
        - Overview: "learningresources/Form_editor_Questionnaire_editor.md"
        - Form Editor 17.1: "learningresources/Form_editor_17_1.md"
        - Rubric: "learningresources/Rubric.md"
        - Question rules: "learningresources/Question_rules.md"
    - Portfolio 2.0 Template:
      - Portfolio template Creation: "learningresources/Portfolio_template_Creation.md"
      - Portfolio template Administration and editing: "learningresources/Portfolio_template_Administration_and_editing.md"
      - Forms in the ePortfolio template: "learningresources/Forms_in_the_ePortfolio_template.md"
    - Glossary:
      - Overview: "learningresources/Glossary.md"
   
  - Groups:
    - groups/index.md
    - Create Groups: "groups/Create_Groups.md"
    - Using Group Tools: "groups/Using_Group_Tools.md"
    - Administration: 
      - Group Administration: "groups/Group_Administration.md"
      - LTI access: "groups/LTI_Share_groups.md"

  - Help:
    - help/index.md
    - Course Problems and Error Messages: "help/Course_Problems_and_Error_Messages.md"

  - About us:
    - about/index.md
    - Information on OpenOlat: "about/Information_on_OpenOlat.md"
    - The Idea of Open-Source Software: "about/OpenSource_Software.md"
